In [1]:
# import libraries

import pandas as pd
import numpy as np
import os
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import matplotlib.pyplot as plt
from datetime import datetime as dt

In [2]:
#set path
path = r'C:\Users\nrsmi\Documents\CareerFoundry\New_York_CitiBike_Analysis'

In [3]:
# import df
df = pd.read_csv(os.path.join(path, 'Data', 'Prepared_Data', 'Weather_DailyBikeRides_RideDuration_cleaned.csv'), index_col = 0 )

C:\Users\nrsmi\AppData\Local\Temp\ipykernel_14664\2100087590.py:2: DtypeWarning: Columns (7,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(path, 'Data', 'Prepared_Data', 'Weather_DailyBikeRides_RideDuration_cleaned.csv'), index_col = 0 )

In [4]:
df.head()

,date,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,avgTemp,bike_rides_daily,ride_duration
0,2022-01-01,4A091640AEC83471,classic_bike,2022-01-01 16:01:22.082,2022-01-01 16:05:11.986,S 4 St & Wythe Ave,5204.05,Kent Ave & S 11 St,5062.01,40.712859,-73.965903,40.707645,-73.968415,member,11.6,20428,3.831733
1,2022-01-01,7A560D6287C00126,classic_bike,2022-01-01 14:07:04.344,2022-01-01 14:31:57.500,Lexington Ave & E 120 St,7652.04,Amsterdam Ave & W 125 St,7800.03,40.801307,-73.939817,40.813358,-73.956461,member,11.6,20428,24.885933
2,2022-01-01,4F6F726B809C15E4,classic_bike,2022-01-01 12:02:26.943,2022-01-01 12:14:13.555,Lexington Ave & E 120 St,7652.04,Amsterdam Ave & W 125 St,7800.03,40.801307,-73.939817,40.813358,-73.956461,member,11.6,20428,11.776867
3,2022-01-01,3BC10DC94FD79955,classic_bike,2022-01-01 22:53:23.508,2022-01-01 23:18:42.881,Cleveland Pl & Spring St,5492.05,Mott St & Prince St,5561.04,40.722104,-73.997249,40.723180,-73.994800,member,11.6,20428,25.322883
4,2022-01-01,FE4CE7F1CFFD7952,classic_bike,2022-01-01 08:04:51.755,2022-01-01 08:08:07.290,Central Park North & Adam Clayton Powell Blvd,7617.07,E 110 St & Madison Ave,7587.14,40.799484,-73.955613,40.796154,-73.947821,member,11.6,20428,3.258917

In [5]:
# Create a copy with fewer columns 

df_1 = df.drop(columns = {'started_at', 'ended_at', 'ride_id', 
'rideable_type', 'start_station_id', 'end_station_id', 'member_casual'})

In [6]:
import gc # this is garbage collector - speeds up performance
gc.collect()

0

In [7]:
df_1.head()

,date,start_station_name,end_station_name,start_lat,start_lng,end_lat,end_lng,avgTemp,bike_rides_daily,ride_duration
0,2022-01-01,S 4 St & Wythe Ave,Kent Ave & S 11 St,40.712859,-73.965903,40.707645,-73.968415,11.6,20428,3.831733
1,2022-01-01,Lexington Ave & E 120 St,Amsterdam Ave & W 125 St,40.801307,-73.939817,40.813358,-73.956461,11.6,20428,24.885933
2,2022-01-01,Lexington Ave & E 120 St,Amsterdam Ave & W 125 St,40.801307,-73.939817,40.813358,-73.956461,11.6,20428,11.776867
3,2022-01-01,Cleveland Pl & Spring St,Mott St & Prince St,40.722104,-73.997249,40.723180,-73.994800,11.6,20428,25.322883
4,2022-01-01,Central Park North & Adam Clayton Powell Blvd,E 110 St & Madison Ave,40.799484,-73.955613,40.796154,-73.947821,11.6,20428,3.258917

In [8]:
np.random.seed(32)
red = np.random.rand(len(df_1)) <= 0.92

In [9]:
small = df_1[~red]
small.shape

(2379383, 10)

In [10]:
small.head()

,date,start_station_name,end_station_name,start_lat,start_lng,end_lat,end_lng,avgTemp,bike_rides_daily,ride_duration
3,2022-01-01,Cleveland Pl & Spring St,Mott St & Prince St,40.722104,-73.997249,40.723180,-73.994800,11.6,20428,25.322883
7,2022-01-01,Broadway & E 14 St,E 25 St & 1 Ave,40.734546,-73.990741,40.738177,-73.977387,11.6,20428,10.860767
25,2022-01-01,28 Ave & 35 St,Vernon Blvd & 30 Rd,40.767100,-73.916986,40.770845,-73.934171,11.6,20428,9.277000
44,2022-01-01,Bergen St & Smith St,Atlantic Ave & Furman St,40.686744,-73.990632,40.691652,-73.999979,11.6,20428,3.747900
58,2022-01-01,Schermerhorn St & Bond St,Smith St & 3 St,40.688417,-73.984517,40.678724,-73.995991,11.6,20428,5.517417

In [15]:
small.tail()

,date,start_station_name,end_station_name,start_lat,start_lng,end_lat,end_lng,avgTemp,bike_rides_daily,ride_duration
29838138,2022-12-31,Cathedral Pkwy & Broadway,W 20 St & 8 Ave,40.804283,-73.967036,40.743453,-74.000040,8.2,31466,24.208233
29838141,2022-12-31,Park Cir & East Dr,6 Ave & 9 St,40.651531,-73.972160,40.668127,-73.983776,8.2,31466,8.483000
29838144,2022-12-31,Division St & Bowery,Sands St & Jay St,40.714193,-73.996732,40.700119,-73.986200,8.2,31466,14.896450
29838146,2022-12-31,MacDonough St & Marcy Ave,Centre St & Chambers St,40.680808,-73.946169,40.712733,-74.004607,8.2,31466,47.059183
29838161,2022-12-31,White St & Moore St,Bleecker St & Crosby St,40.704508,-73.935100,40.726156,-73.995102,8.2,31466,25.647550

In [11]:
# small.to_csv(os.path.join(path, 'Data','Prepared_Data', 'reduced_data_to_plot_7.csv'),index = False)

In [16]:
small.columns

Index(['date', 'start_station_name', 'end_station_name', 'start_lat',
       'start_lng', 'end_lat', 'end_lng', 'avgTemp', 'bike_rides_daily',
       'ride_duration'],
      dtype='object')

In [18]:
# Group by start station and calculate the average ride duration
top_20_stations = (
    small.groupby("start_station_name")
    ["ride_duration"].mean()
    .nlargest(20)
    .reset_index()
)

# Display the resulting dataframe
top_20_stations

                                   start_station_name  ride_duration
0                                       2 Ave & 43 St     723.583733
1                                 Broad St & Water St     535.127795
2                                 South St & Broad St     460.980777
3                            Frost St & Debevoise Ave     402.962404
4                                    E 118 St & 3 Ave     223.875140
5                             Dwight St & Van Dyke St     155.052056
6                                 21 Ave & Shore Blvd     144.727767
7                               Yankee Ferry Terminal     142.426893
8                               Walton Ave & E 168 St      74.412604
9   57 St & 1 Ave - Brooklyn Army Terminal Vaccina...      72.931730
10                        Sterling Pl & Rochester Ave      71.703300
11                            Wakeman Pl & Ridge Blvd      68.830691
12                           W 34 St &\tHudson Blvd E      63.109827
13                              LaGuardia Pl & W 3 St      61.944649
14                                 W 37 St & Broadway      60.594602
15                                Broadway\t& W 48 St      52.987444
16                                   Soissons Landing      51.878233
17                                      Old Fulton St      50.480956
18                              Dyckman St & Staff St      45.566787
19                      Brooklyn Bridge Park - Pier 2      45.387412

In [19]:
top_20_stations.to_csv(os.path.join(path, 'Data','Prepared_Data', 'RideDuration_top20.csv'),index = False)

In [22]:
RideDuration_top20 = pd.read_csv(os.path.join(path, 'Data', 'Prepared_Data', 'RideDuration_top20.csv'))

In [23]:
RideDuration_top20.head()

         start_station_name  ride_duration
0             2 Ave & 43 St     723.583733
1       Broad St & Water St     535.127795
2       South St & Broad St     460.980777
3  Frost St & Debevoise Ave     402.962404
4          E 118 St & 3 Ave     223.875140